"""frist migration

Revision ID: 3ee8ba19c623
Revises: 
Create Date: 2025-07-06 14:36:46.664251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee8ba19c623'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sneakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.Enum('RUNNING', 'BASKETBALL', 'LIFESTYLE', 'TRAINING', name='categoryenum', native_enum=False), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('image_filename', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sneakers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sneakers_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_sneakers_price'), ['price'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sneakers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sneakers_price'))
        batch_op.drop_index(batch_op.f('ix_sneakers_category'))

    op.drop_table('sneakers')
    # ### end Alembic commands ###
